/**
 * Generative UI Component Renderer
 * 
 * Implements AG-UI Generative UI protocol for dynamically rendering
 * UI components generated by agents.
 * 
 * Reference: https://ag-ui.com/
 */
import React, { useState, useCallback } from 'react';
import type { UIComponent, UIUpdate, UIRemove } from '../types/events';
import './GenerativeUI.css';

// Component registry - maps component_type to React component
type ComponentRenderer = (props: any, onInteraction: (type: string, data: any) => void) => React.ReactNode;

interface ComponentRegistry {
    [componentType: string]: ComponentRenderer;
}

// Built-in component renderers
const builtInComponents: ComponentRegistry = {
    // Button component
    button: (props: any, onInteraction: (type: string, data: any) => void) => {
        const { label, variant = 'primary', disabled = false, onClick, ...rest } = props;
        return (
            <button
                className={`genui-button genui-button-${variant}`}
                disabled={disabled}
                onClick={() => {
                    onInteraction('click', { ...rest });
                    if (onClick) onClick();
                }}
                {...rest}
            >
                {label || props.children || 'Button'}
            </button>
        );
    },

    // Image component
    image: (props: any) => {
        const { src, alt = '', width, height, ...rest } = props;
        // Handle relative URLs - convert to absolute
        let imageSrc = src;
        if (src && typeof src === 'string') {
            if (src.startsWith('/api/v1/files/')) {
                imageSrc = `http://localhost:8000${src}`;
            } else if (!src.startsWith('http://') && !src.startsWith('https://') && !src.startsWith('data:')) {
                // Assume it's a relative path
                imageSrc = `http://localhost:8000/api/v1/files/${src}`;
            }
        }
        return (
            <img
                src={imageSrc}
                alt={alt}
                width={width}
                height={height}
                className="genui-image"
                onError={() => {
                    console.error('Failed to load image:', imageSrc);
                }}
                {...rest}
            />
        );
    },

    // Card component
    card: (props: any, onInteraction: (type: string, data: any) => void) => {
        const { title, content, children, onClick, ...rest } = props;
        return (
            <div
                className="genui-card"
                onClick={() => {
                    if (onClick) {
                        onInteraction('click', { ...rest });
                        onClick();
                    }
                }}
                {...rest}
            >
                {title && <div className="genui-card-title">{title}</div>}
                <div className="genui-card-content">
                    {content || children}
                </div>
            </div>
        );
    },

    // Form component
    form: (props: any, onInteraction: (type: string, data: any) => void) => {
        const { fields = [], onSubmit, ...rest } = props;
        const [formData, setFormData] = useState<Record<string, any>>({});

        const handleSubmit = (e: React.FormEvent) => {
            e.preventDefault();
            onInteraction('submit', { data: formData, ...rest });
            if (onSubmit) onSubmit(formData);
        };

        const handleChange = (name: string, value: any) => {
            setFormData(prev => ({ ...prev, [name]: value }));
            onInteraction('change', { field: name, value, ...rest });
        };

        return (
            <form className="genui-form" onSubmit={handleSubmit} {...rest}>
                {fields.map((field: any, idx: number) => (
                    <div key={idx} className="genui-form-field">
                        {field.label && <label>{field.label}</label>}
                        {field.type === 'text' || field.type === 'email' || field.type === 'password' ? (
                            <input
                                type={field.type}
                                name={field.name}
                                placeholder={field.placeholder}
                                value={formData[field.name] || ''}
                                onChange={(e) => handleChange(field.name, e.target.value)}
                                required={field.required}
                            />
                        ) : field.type === 'textarea' ? (
                            <textarea
                                name={field.name}
                                placeholder={field.placeholder}
                                value={formData[field.name] || ''}
                                onChange={(e) => handleChange(field.name, e.target.value)}
                                required={field.required}
                            />
                        ) : field.type === 'select' ? (
                            <select
                                name={field.name}
                                value={formData[field.name] || ''}
                                onChange={(e) => handleChange(field.name, e.target.value)}
                                required={field.required}
                            >
                                {field.options?.map((opt: any) => (
                                    <option key={opt.value} value={opt.value}>
                                        {opt.label}
                                    </option>
                                ))}
                            </select>
                        ) : null}
                    </div>
                ))}
                <button type="submit" className="genui-button genui-button-primary">
                    {props.submitLabel || 'Submit'}
                </button>
            </form>
        );
    },

    // Text component
    text: (props: any) => {
        const { content, variant = 'body', ...rest } = props;
        const Tag = variant === 'heading' ? 'h3' : variant === 'subheading' ? 'h4' : 'p';
        return (
            <Tag className={`genui-text genui-text-${variant}`} {...rest}>
                {content || props.children}
            </Tag>
        );
    },

    // Container component
    container: (props: any, _onInteraction: (type: string, data: any) => void) => {
        const { children, layout = 'vertical', ...rest } = props;
        return (
            <div
                className={`genui-container genui-container-${layout}`}
                {...rest}
            >
                {children}
            </div>
        );
    },

    // Video component
    video: (props: any) => {
        const { src, controls = true, width, height, ...rest } = props;
        return (
            <video
                src={src}
                controls={controls}
                width={width}
                height={height}
                className="genui-video"
                {...rest}
            >
                Your browser does not support the video tag.
            </video>
        );
    },

    // Audio component
    audio: (props: any) => {
        const { src, controls = true, ...rest } = props;
        // Handle relative URLs
        let audioSrc = src;
        if (src && typeof src === 'string' && src.startsWith('/api/v1/files/')) {
            audioSrc = `http://localhost:8000${src}`;
        }
        return (
            <audio
                src={audioSrc}
                controls={controls}
                className="genui-audio"
                {...rest}
            >
                Your browser does not support the audio tag.
            </audio>
        );
    },

    // File list component
    file_list: (props: any, onInteraction: (type: string, data: any) => void) => {
        const { files = [], onFileClick, ...rest } = props;
        return (
            <div className="genui-file-list" {...rest}>
                {files.map((file: any, idx: number) => (
                    <div
                        key={idx}
                        className={`genui-file-item ${file.is_directory ? 'genui-file-item-directory' : ''} ${file.is_image ? 'genui-file-item-image' : ''}`}
                        onClick={() => {
                            if (onFileClick) {
                                onInteraction('file_click', { file, ...rest });
                                onFileClick(file);
                            }
                        }}
                    >
                        {file.is_image ? (
                            <div className="genui-file-item-preview">
                                <img
                                    src={file.url.startsWith('http') ? file.url : `http://localhost:8000${file.url}`}
                                    alt={file.name}
                                    className="genui-file-item-thumbnail"
                                />
                            </div>
                        ) : file.is_directory ? (
                            <div className="genui-file-item-icon">📁</div>
                        ) : (
                            <div className="genui-file-item-icon">📄</div>
                        )}
                        <div className="genui-file-item-info">
                            <div className="genui-file-item-name">{file.name}</div>
                            {file.size && (
                                <div className="genui-file-item-size">
                                    {(file.size / 1024).toFixed(2)} KB
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>
        );
    },

    // Image gallery component
    image_gallery: (props: any, onInteraction: (type: string, data: any) => void) => {
        const { images = [], columns = 3, onImageClick, ...rest } = props;
        return (
            <div
                className="genui-image-gallery"
                style={{ gridTemplateColumns: `repeat(${columns}, 1fr)` }}
                {...rest}
            >
                {images.map((image: any, idx: number) => {
                    const imageUrl = typeof image === 'string' 
                        ? (image.startsWith('http') ? image : `http://localhost:8000/api/v1/files/${image}`)
                        : (image.url?.startsWith('http') ? image.url : `http://localhost:8000${image.url || image.src}`);
                    const imageAlt = typeof image === 'string' ? `Image ${idx + 1}` : (image.alt || image.name || `Image ${idx + 1}`);
                    
                    return (
                        <div
                            key={idx}
                            className="genui-image-gallery-item"
                            onClick={() => {
                                // Open image in new tab for preview
                                window.open(imageUrl, '_blank');
                                if (onImageClick) {
                                    onInteraction('image_click', { image, index: idx, ...rest });
                                    onImageClick(image, idx);
                                }
                            }}
                        >
                            <img
                                src={imageUrl}
                                alt={imageAlt}
                                className="genui-image-gallery-thumbnail"
                            />
                        </div>
                    );
                })}
            </div>
        );
    },
};

interface GenerativeUIProps {
    component: UIComponent;
    onInteraction?: (componentId: string, interactionType: string, data: any) => void;
    customComponents?: ComponentRegistry;
}

export const GenerativeUI: React.FC<GenerativeUIProps> = ({
    component,
    onInteraction,
    customComponents = {}
}) => {
    const handleInteraction = useCallback((type: string, data: any) => {
        if (onInteraction) {
            onInteraction(component.component_id, type, data);
        }
    }, [component.component_id, onInteraction]);

    // Merge custom components with built-in components
    const componentRegistry = { ...builtInComponents, ...customComponents };

    // Get renderer for this component type
    const renderer = componentRegistry[component.component_type];

    if (!renderer) {
        // Fallback: render as JSON if component type not found
        return (
            <div className="genui-unknown">
                <div className="genui-unknown-type">Unknown component: {component.component_type}</div>
                <pre>{JSON.stringify(component.props, null, 2)}</pre>
            </div>
        );
    }

    // Render component with children if present
    const renderedChildren = component.children?.map((child, idx) => {
        // If child is a component descriptor, render it recursively
        if (child.component_type) {
            return (
                <GenerativeUI
                    key={child.component_id || idx}
                    component={child as UIComponent}
                    onInteraction={onInteraction}
                    customComponents={customComponents}
                />
            );
        }
        // Otherwise render as raw content
        return <React.Fragment key={idx}>{JSON.stringify(child)}</React.Fragment>;
    });

    // Render the component
    const rendered = renderer(
        { ...component.props, children: renderedChildren },
        handleInteraction
    );

    return <div className="genui-wrapper" data-component-id={component.component_id}>
        {rendered}
    </div>;
};

// Component manager for handling multiple components
interface ComponentState {
    [componentId: string]: UIComponent;
}

export const useGenerativeUI = () => {
    const [components, setComponents] = useState<ComponentState>({});

    const addComponent = useCallback((component: UIComponent) => {
        setComponents(prev => ({
            ...prev,
            [component.component_id]: component
        }));
    }, []);

    const updateComponent = useCallback((update: UIUpdate) => {
        setComponents(prev => {
            const existing = prev[update.component_id];
            if (!existing) return prev;

            return {
                ...prev,
                [update.component_id]: {
                    ...existing,
                    props: update.merge
                        ? { ...existing.props, ...update.props }
                        : update.props
                }
            };
        });
    }, []);

    const removeComponent = useCallback((remove: UIRemove) => {
        setComponents(prev => {
            const { [remove.component_id]: _, ...rest } = prev;
            return rest;
        });
    }, []);

    return {
        components,
        addComponent,
        updateComponent,
        removeComponent
    };
};

